---
title: "usecase_ogimet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## USE CASE - Ogimet - Stopniodni 2013-2018

1. Pobieranie danych dobowych ze stacji synoptycznych  z bazy ogimet
2. Wybranie tylko interesującego przedziału czasu (np. 2013/01/01-2018/12/31)
3. Wybranie tylko tempe

```{r,warning=FALSE}
library(tidyr)
library(remotes)
install_github("bczernecki/imgw")
library(imgw)
library(dplyr)
library(climatol)
# pobieranie danych:
df <-  ogimet_hourly(date = c("2018-01-01","2018-12-31"),station = c("01008"))
#przygotowanie pod róże wiatrów
df %>%
  select(ddd,ffkmh)%>%
  mutate(rank=if_else(ffkmh<10,"0-10",if_else(ffkmh<20,"10-20",if_else(ffkmh<30,"20-30",">30"))))%>%
  group_by(ddd,rank)%>%
  summarise(amount=n())%>%
  spread(key =ddd,amount)->to_rose
nazwy=as.matrix(to_rose[c(2,3,4,1),1])

to_rose=to_rose[c(2,3,4,1),2:18]
rownames(to_rose)=nazwy


# róża wiatru
rosavent(to_rose, 6, 5, ang=-3*pi/16, main="Annual windrose in 2018",uni = "km/h")
```

